### ISSUE TITLE
tag page is unintuitive

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/sesync-ci.github.io#1]
Something about font/icon sizes makes the tags page seem hard to navigate. Might help to have the tags sidebar on the tags page stay on the right side?

**Comment by itcarroll** [comment]
how did you do the accordion TOC on Jekyll? using that style of tag list on the side could help too.

**Comment by khondula** [comment]
I'm not sure where it is defined, but the reference to accordion is in this file: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages/_includes/docs_nav.html (from the jekyll doc theme: https://aksakalli.github.io/jekyll-doc-theme/). I think the info in the accordion is populated from however many pages are in the _docs folder. I was able to modify it for the research page here: https://palmerlab-umd.github.io/research/home/

**Comment by itcarroll** [comment]
There should probably be a single tag view. Ideally the TOC listing all tags would remain on the left.

**Comment by itcarroll** [comment]
Removed too-long list of tags in 9c9d3218bfa2b6af1c1e9ea85024da7e925a4374. Closing in favor of a tag filtering solution noted in #63.
