### ISSUE TITLE
how do i change my password

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#11]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/How%20do%20I%20change%20my%20Password.aspx

**Comment by eddiem16** [comment]
[Drafted](https://github.com/SESYNC-ci/sesync-ci.github.io/blob/master/_posts/2017-12-18-password.md)

**Comment by eddiem16** [comment]
Finally added photos and correctly formatted page
