### ISSUE TITLE
what resources are available in the conference rooms

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#16]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/What%20resources%20are%20available%20in%20the%20conference%20rooms.aspx

**Comment by eddiem16** [comment]
[Drafted](https://github.com/SESYNC-ci/sesync-ci.github.io/blob/master/_posts/2018-01-11-Conference-Room-Resources.md)

**Comment by eddiem16** [comment]
Done
