### ISSUE TITLE
how do i manage my mailing list

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#17]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/How%20do%20I%20manage%20my%20mailing%20list.aspx

**Comment by eddiem16** [comment]
[Drafted](https://github.com/SESYNC-ci/sesync-ci.github.io/blob/master/_posts/2017-12-18-mailing-list.md)

**Comment by eddiem16** [comment]
Done
