### ISSUE TITLE
how do i add subscribers

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#18]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/How%20do%20I%20add%20subscribers.aspx

**Comment by eddiem16** [comment]
Merging into https://github.com/SESYNC-ci/sesync-ci.github.io/issues/17

and https://github.com/SESYNC-ci/sesync-ci.github.io/blob/master/_posts/2017-12-18-mailing-list.md

**Comment by eddiem16** [comment]
Finished
