### ISSUE TITLE
add "improve this page" button

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#2]
to _layouts/default.html

example: https://aksakalli.github.io/jekyll-doc-theme/docs/customization/

**Comment by timtheguy** [comment]
Hi, @itcarroll - interested in helping you in your project! Can I have this issue, and some more details as to what you were imagining for the "Improve this Page" button?

**Comment by itcarroll** [comment]
Hi @timtheguy. Thanks for your interest in contributing. This page is in very early development, so current organization members will be handling all issues for now.
