### ISSUE TITLE
whats the procedure for having remote participants at my meeting

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#20]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/What%27s%20the%20procedure%20for%20having%20remote%20participants%20at%20my%20meeting.aspx

**Comment by eddiem16** [comment]
[Drafted](https://github.com/SESYNC-ci/sesync-ci.github.io/blob/master/_posts/2018-01-12-remote-participants.md)

**Comment by eddiem16** [comment]
Need to add link to/create page for using ebeam 
Need to add pdf of Skype remote instructions
