### ISSUE TITLE
Where are the instructions for connecting to a video conference

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#21]
https://collab.sesync.org/sites/support/SiteAssets/Frequently%20Asked%20Questions/What%27s%20the%20procedure%20for%20having%20remote%20participants%20at%20my%20meeting/Skype%20Instructions%20-%20remote.pdf

**Comment by elizabethtgreen** [comment]
Created faq and attached pdf instructions
