### ISSUE TITLE
When does SESYNC setup my groups resources

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#24]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/When%20does%20SESYNC%20setup%20my%20groups%20resources.aspx

**Comment by eddiem16** [comment]
[Drafted](https://github.com/SESYNC-ci/sesync-ci.github.io/blob/master/_posts/2017-12-18-group-resources.md)

**Comment by eddiem16** [comment]
Finished
