### ISSUE TITLE
Bulk uploading using Cyberduck

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#28]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/Uploading%20files%20using%20Cyberduck.aspx

**Comment by BillSchenk** [comment]
changing the ticket to use FileZilla for OSX and Windows. Writing up a quickstart

**Comment by BillSchenk** [comment]
[page](../blob/master/_posts/2017-12-18-Bulk-upload-download-FileZilla.md)

**Comment by BillSchenk** [comment]
all set.
