### ISSUE TITLE
How do I access SESYNC's data storage

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#29]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/How%20do%20I%20access%20SESYNC%27s%20data%20storage.aspx

**Comment by itcarroll** [comment]
[First draft.](../blob/master/_posts/2017-10-06-research-data-directory.md)

**Comment by itcarroll** [comment]
Rename to "Research Data Directory".

**Comment by itcarroll** [comment]
Combine with "Bulk uploading or downloading ..." : http://cyberhelp.sesync.org/quickstart/Bulk-upload-download-FileZilla.html

**Comment by elizabethtgreen** [comment]
Included instructions to connect to data directory through ssh and linked to bulk uploading and downloading
