### ISSUE TITLE
Why does does my Virtual Machine show less memory than I requested

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#34]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/Why%20does%20does%20my%20Virtual%20Machine%20show%20less%20memory%20than%20I%20requested.aspx

**Comment by BillSchenk** [comment]
[draft](../blob/master/_posts/2017-12-18-windows-dynamic-memory.md)
