### ISSUE TITLE
How do I create a new Git Project

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#35]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/How%20do%20I%20create%20a%20new%20Git%20Project.aspx

**Comment by elizabethtgreen** [comment]
needs link to How do I create an R Studio Project from Git ([[37]](https://github.com/SESYNC-ci/sesync-ci.github.io/issues/37))
