### ISSUE TITLE
How do I create an R Studio Project from Git

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#37]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/How%20do%20I%20create%20an%20R%20Studio%20Project%20from%20Git.aspx

**Comment by mshelley1** [comment]
The collab pages on the cluster need master reorg. Decided to create an FAQ about the cluster, a quick start quide about connecting to the cluster, and a blog post with the example RStudio submission

**Comment by itcarroll** [comment]
Extracting some content from a different [quickstart](https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/How%20do%20I%20use%20R%20Studio.aspx) that might be used on this page:

***

# Sharing an R project

We strongly encourage groups to use a version control system/code sharing system
such as GitHub or GitLab to manage sharing between group members. SESYNC
provides a free gitlab service which will allow groups to create private
repositories. Please see our \[\[How do I create a new Git Project\]\] guide for
more information on using this service.

Even if you don't plan on sharing your code with others, we recommend you use
gitlab or github to track your code. This has the advantage of allowing you to
easily rollback changes; invite SESYNC staff to assist in debugging your code;
and copy your code to your own laptop or desktop.

Creating a shared project is a two step process. A single group member first
creates a git repository repository for the project and some initial code; then
everyone else in the group clones a copy to their own directory.

## Creating the Project (one person)  

1. Create a new Gitlab or Github project and copy the URL for the project (e.g.,
https://gitlab.sesync.org/groupname/project.git)
    
2. Add your group members to the newly created project.

3. The first group member should create a new project in R Studio by doing the following:

    1. Create a new project and choose Version Control for the project type and
    select Git as the type of versioned project.
    
    2.  Use the URL from step one as the 'Repository URL' for your new project.

5.  After you've created a project, create your initial R code and a README.md
describing your code.

6.  When your finished editing your code and would like to give others access to
it, do a git Commit (Tools -> Version Control -> Commit), followed by a Push
(Tools -> Version Control -> Push Branch)
    
## Cloning the Project

1. All other group members will need to create a new RStudio Project the same
way the first person did (File -> New Project -> Version Control -> Git) and
enter the project URL.
    
2. The group members will now be able to see the code that the first person pushed.

**Comment by khondula** [comment]
a00b344be82a1d642aa5ccd0e0b4fa1f356c2561
