### ISSUE TITLE
What is the SESYNC cluster

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#41]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/What%20is%20the%20SESYNC%20cluster.aspx

**Comment by mshelley1** [comment]
#43, #42, #45, #46

**Comment by mshelley1** [comment]
Created FAQ. Left out some details in original collab post (e.g., details of sinfo, squeue)
