### ISSUE TITLE
How do I connect to the cluster

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#42]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/How%20do%20I%20connect%20to%20the%20cluster.aspx

**Comment by mshelley1** [comment]
Created a quick start guide. Quick start guide needs more info/details on ssh submission and on setting partition. Detailed partition info available in "what is the cluster" faq.

#41, #43, #45, #46

**Comment by itcarroll** [comment]
Here's the [current quickstart](../blob/master/_posts/2018-01-18-Using-the-SESYNC-Cluster.md) that needs updating.

I suggest combining the [Cluster Python](../blob/master/_posts/2018-01-18-how-to-run-Python-scripts-on-the-cluster.md) and [Cluster R](../blob/master/_posts/2018-01-18-how-do-i-submit-an-r-script.md) quickstarts into this one, so there is only one Quickstart about cluster computing.

**Comment by itcarroll** [comment]
Re-created as 29179 on redmine.
