### ISSUE TITLE
What happens to my jobs during your maintenance window

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#47]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/What%20happens%20to%20my%20jobs%20during%20your%20maintenance%20window.aspx

**Comment by eddiem16** [comment]
[Drafted](https://github.com/SESYNC-ci/sesync-ci.github.io/blob/master/_posts/2017-12-18-maintenance-window-slurm.md)

**Comment by eddiem16** [comment]
Good to go!
