### ISSUE TITLE
How do I publish a Shiny app on the SESYNC server

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#48]
https://collab.sesync.org/sites/support/Frequently%20Asked%20Questions/How%20do%20I%20publish%20a%20Shiny%20app%20on%20the%20SESYNC%20server.aspx

**Comment by elizabethtgreen** [comment]
needs link to How do I create an R Studio Project from Git ([[37]](https://github.com/SESYNC-ci/sesync-ci.github.io/issues/37))
