### ISSUE TITLE
Monthly Maintenance Window

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#52]
https://base.sesync.org/projects/documentation/wiki/MaintenanceWindow

- https://base.sesync.org/projects/documentation/wiki/Windows_Updates
- https://base.sesync.org/projects/documentation/wiki/Mac_OS-X_Updates

**Comment by BillSchenk** [comment]
[draft](../blob/master/_posts/2017-12-18-monthly-maintenance-window.md)

**Comment by BillSchenk** [comment]
all set, linked to SLURM subpage
