### ISSUE TITLE
What resources are available?

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#60]

**Comment by itcarroll** [comment]
Copy from PDF that Bill created for post-wildfire (in sesync-ci sharepoint site).

**Comment by BillSchenk** [comment]
Text done, will need to add PDF link once we have it finalized

**Comment by itcarroll** [comment]
@BillSchenk What's the goal here? To have "SESYNC Research IT Resources.docx" linked from this site and elsewhere (where would that be?)

**Comment by BillSchenk** [comment]
Goal is to have the .docx (or PDF, we can convert) downloadable via cyberhelp.sesync.org

the docx currently lives in SESYNC CI documents on O365

**Comment by itcarroll** [comment]
And it doesn't have to continue being available through sharepoint anywhere, right? I'll move it to github.

**Comment by BillSchenk** [comment]
I would keep a copy/draft in our O365 SESYNC CI Sharepoint documents
library in case we need to edit it in the future or we want to directly
send to (or print) a user/group. It is not currently on collab.sesync.org.

**Comment by BillSchenk** [comment]
also, it needs updating, still references collab.sesync.org, and could use a once-over for formatting fixes.

**Comment by mshelley1** [comment]
See #63

**Comment by itcarroll** [comment]
updated the document on 0365. noted in #63 that we need link, so closing here.
