### ISSUE TITLE
FAQ organizational suggestions

### ISSUE THREAD

**Issue by mshelley1** [SESYNC-ci/sesync-ci.github.io#63]
Looked through existing and outstanding. Suggesting following  categories based on frequency of topic in FAQ:

- The Big Picture (for "what resources", "what support", and policies)
- Windows VM
- Git
- [something snappy yet descriptive for main research resources] (linux resources, storage, cluster, R/db, shiny)
- SESYNC Accounts
- Maintenance
- General [or Other] (everything else)

**Comment by BillSchenk** [comment]
> [something snappy yet descriptive for main research resources] (linux resources, storage, cluster, R/db, shiny)

infrastructure?

What's the plan to "categorize" ? more formating / sorting ot top-level FAQ page?

seems that most of the categories listed have tags closely associated with them, can we organize by tag (i.e. first tags?)

**Comment by BillSchenk** [comment]
http://drejkim.com/blog/2015/03/18/filtering-posts-by-tags-with-jekyll/

**Comment by itcarroll** [comment]
Sticky at the top
- [x] what resources are available
- [x] how do i change password / what's my sesync username (combine)
- [x] how do i get help

Also sticky a quick start
- [x] link to docx

Try to do a tag filtering thingy (now #72)

**Comment by mshelley1** [comment]
Update "What resources are available FAQ" to include a link to Bill's PDF "for more detail"

Use tags to filter from the top and make sticky certain FAQ for next version
