### ISSUE TITLE
who has used what

### ISSUE THREAD

**Issue by itcarroll** [SESYNC-ci/sesync-ci.github.io#7]
https://collab.sesync.org/sites/support/_layouts/15/start.aspx#/Lists/Who%20has%20used%20what/Allitemsg.aspx#InplviewHashea35e96a-9cc4-4df5-baf2-a5033e22749a=ShowInGrid%3DTrue

**Comment by itcarroll** [comment]
Export to sharepoint/old_collab

**Comment by BillSchenk** [comment]
creating redmine ticket
