### ISSUE TITLE
Add documentation for using slurm cluster with --time options

### ISSUE THREAD

**Issue by BillSchenk** [SESYNC-ci/sesync-ci.github.io#75]
need to add a blurb somewhere to demonstrate using --time to submit jobs

**Comment by itcarroll** [comment]
Some instructions I sent Nate to get started ...

From: itrequests@sesync.org [mailto:itrequests@sesync.org] 
Sent: Monday, March 19, 2018 11:21 AM
To: Nate Jones <njones@sesync.org>
Cc: Jenny Zambrano-External <jzambran@umd.edu>; Rob Rankin <rrankin@sesync.org>
Subject: Re: cluster issues [Support #26149]

Hi Nate,

This does have to do with the upcoming maintenance window. Any submitted job that would conflict with an upcoming cluster reservation stays in the queue. You can check for cluster reservations:

```
$ sinfo -T 
RESV_NAME STATE START_TIME END_TIME DURATION NODELIST
april10-18-poweroutage INACTIVE 2018-04-10T08:00:00 2018-04-11T08:00:00 1-00:00:00 pn[24-43]
march18outage INACTIVE 2018-03-22T08:00:00 2018-03-23T00:00:00 16:00:00 pn[24-43]
```

You can use the sbatch "--time" argument to specify a hard limit for your job (i.e. it will be killed if it runs over the given amount of time). With that information, the job scheduler will know if it can start your job before the reservation.

Take care,
Ian

**Comment by itcarroll** [comment]
Moved to 29178 in redmine.
